version: "3.10"

services:
  app:
    ipc: host
    build: .
    container_name: faf-ga-pipeline
    working_dir: /app
    volumes:
      - .:/app
    environment:
      PYTHONUNBUFFERED: 1
      FILE_IN: FAF_files.csv
      OUT_DIR: results
    gpus: all
    tty: true
    stdin_open: true
    command: ["bash", "-lc", "bash run_pipeline.sh"]
